 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/upload_csvs", type: :request do
  # UploadCsv. As you add validations to UploadCsv, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UploadCsv.create! valid_attributes
      get upload_csvs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      upload_csv = UploadCsv.create! valid_attributes
      get upload_csv_url(upload_csv)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_upload_csv_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      upload_csv = UploadCsv.create! valid_attributes
      get edit_upload_csv_url(upload_csv)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UploadCsv" do
        expect {
          post upload_csvs_url, params: { upload_csv: valid_attributes }
        }.to change(UploadCsv, :count).by(1)
      end

      it "redirects to the created upload_csv" do
        post upload_csvs_url, params: { upload_csv: valid_attributes }
        expect(response).to redirect_to(upload_csv_url(UploadCsv.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UploadCsv" do
        expect {
          post upload_csvs_url, params: { upload_csv: invalid_attributes }
        }.to change(UploadCsv, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post upload_csvs_url, params: { upload_csv: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested upload_csv" do
        upload_csv = UploadCsv.create! valid_attributes
        patch upload_csv_url(upload_csv), params: { upload_csv: new_attributes }
        upload_csv.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the upload_csv" do
        upload_csv = UploadCsv.create! valid_attributes
        patch upload_csv_url(upload_csv), params: { upload_csv: new_attributes }
        upload_csv.reload
        expect(response).to redirect_to(upload_csv_url(upload_csv))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        upload_csv = UploadCsv.create! valid_attributes
        patch upload_csv_url(upload_csv), params: { upload_csv: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested upload_csv" do
      upload_csv = UploadCsv.create! valid_attributes
      expect {
        delete upload_csv_url(upload_csv)
      }.to change(UploadCsv, :count).by(-1)
    end

    it "redirects to the upload_csvs list" do
      upload_csv = UploadCsv.create! valid_attributes
      delete upload_csv_url(upload_csv)
      expect(response).to redirect_to(upload_csvs_url)
    end
  end
end
